[platformio]
description = Surfboard Display
src_dir = ./

[env:main_display]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = 
	-D DISABLE_LORA=1
lib_deps =
	me-no-dev/AsyncTCP@^1.1.1
	me-no-dev/ESPAsyncWebServer
	ESP32Servo
	olikraus/U8g2

[env:remote_display]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags = 
	-D DISABLE_LORA=1
lib_deps =
	me-no-dev/AsyncTCP@^1.1.1
	me-no-dev/ESPAsyncWebServer
	ESP32Servo
	olikraus/U8g2