; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
description = Surfboard Display
src_dir = ./

[env:main_display]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
build_flags = 
lib_deps = 
	me-no-dev/AsyncTCP@^1.1.1
	me-no-dev/ESPAsyncWebServer
	ESP32Servo
	olikraus/U8g2
	jgromes/RadioLib
src_dir = main_display/src
build_src_filter = +<main_display/src/*> -<remote/src/*>
board_build.erase_flash = no
upload_port = COM5
monitor_port = COM5

[env:remote_display]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
build_flags = 
lib_deps = 
	ESP32Servo
	olikraus/U8g2
	jgromes/RadioLib
src_dir = remote_display/src
build_src_filter = +<remote/src/*> -<main_display/src/*>
board_build.erase_flash = no
upload_port = COM12
monitor_port = COM12
